def login_personal(self):
        username = input("Ingrese nombre de usuario: ")
        password = input("Ingrese contraseña: ")
        
        if username == "pablo" and password == "libreriacreaciones":
            print("¡Bienvenido Pablo!")
            # Aquí puedes añadir más funcionalidades para el personal
        else:
            print("Nombre de usuario o contraseña incorrectos.")

pass            